
########################
# jekyll configuration #
########################
baseurl: "/divi-jekyll"

paginate: 15
paginate_path: "/blog/page-:num/"

############
# Defaults #
############

######################
# Site configuration #
######################
divi_version:  "2.6.4.4" #String, your divi version
lang: "en" # String, your lang code.
title: "Another site make with jekyll" # String, your site title.
name: "Divi" # String, your site name.
logo: "http://www.universaal.info/wp-content/uploads/logo.png" # String, logo URL.

boxed_layout:  false #Bool
top_menu: "top_menu.html" #String: filename.extension
display_top_menu : true #Bool
main_sidebar: "main_menu.html" #String: filename.extension
main_menu_style: "standard" # String: "standard", "centred", "side"
display_main_menu : true #Bool
footer: "footer.html" #String: filename.extension
display_footer : true #Bool

#email: 'contact@ourwebsite.com' # String, your email.
#phone: '888-443-2342' # String, your phone.
facebook_url : '#' # String, facebook URL.
twitter_url : '#' # String, twitter URL.
github_url : '#' # String, google+ URL.
youtube_url : '#' # String, google+ URL.
linkedin_url : '#' # String, google+ URL.
google_url : '#' # String, google+ URL.
